### ISSUE TITLE
New version with npm updates

### ISSUE THREAD

**Issue by EvHaus** [xt0rted/stylelint-actions-formatters#61]
Hey @xt0rted, would you mind releasing a new version of this package so that we can pick up some of the `npm` dependency updates you merged in since 0.1.0? Thank you!

**Comment by xt0rted** [comment]
I'll try to get a new version out in the next day or two.

**Comment by EvHaus** [comment]
🙏 Much appreciated!

**Comment by xt0rted** [comment]
Up to v14.1.0 has been published. v14.2.0 has some changes I need to look into before publishing any more versions. I'll get to this tomorrow probably.

**Comment by xt0rted** [comment]
Just published the last of the outstanding versions. The most recent is v14.5.3 which was published earlier today.
